AutoshopMVC/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoshopMVC.Models;
using BAL.Interfaces;
using BAL.Models;
using BAL.Services;
using DAL.Entities;
using javax.jws;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoshopMVC.Controllers
{

    public class AppointmentController : Controller
    {
        private IAppointmentService appointmentService;
        private UserManager<User> _userManager;
        BigAppointmentModel model;

        public AppointmentController(UserManager<User> userManager)
        {
            appointmentService = new AppointmentService();
            _userManager = userManager;
            model = new BigAppointmentModel();
        }

        [Authorize]
        public IActionResult Index()
        {
            return View(model);
        }
        
        [Authorize]
        [HttpPost]
        public IActionResult MakeAppointment(BigAppointmentModel bigAppointment)
        {
            bigAppointment.appointmentModel.CreationUser = _userManager.GetUserAsync(User).Id;
            appointmentService.MakeNewAppointment(bigAppointment.appointmentModel);
            
            return View("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult RefreshAppointments(BigAppointmentModel model)
        {
            model.appointmentsPerDay =  appointmentService.GenerateReports(model.startDate.Date, model.startDate.Date.AddDays(1));
            return View("Index", model);
        }

        [Authorize]
        public IActionResult FinalizeAppointment(int id)
        {
                AppointmentModel appointment = appointmentService.GetAppointment(id);
                appointmentService.FinishAppointment(appointment);
                return View("Index", model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult GenerateReports(BigAppointmentModel model)
        {
            model.generatedAppointmentReports = appointmentService.GenerateReports(model.startDate.Date, model.endDate.Date.AddDays(1));
            return View("Index", model);
        }
    }
}

AutoshopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@using DAL.Entities
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Das Auto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/homeIcon.png" alt="Home" width="42">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="Index">Appointments</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="container-body">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-center text-muted">
        <div class="container">
            &copy; 2020 - Barsan Razvan's Autoshop website - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>